### ISSUE TITLE
Use projectile when available

### ISSUE THREAD

**Issue by langston-barrett** [redguardtoo/eacl#12]
Projectile is a good tool for finding the project root, it includes a bunch of heuristics out of the box. It should be more reliable than just looking for e.g. `.git/` directories.

**Comment by redguardtoo** [comment]
sure. I can use projectile api. Let me have a look

**Comment by redguardtoo** [comment]
fe0091e integration with projectile and find-file-in-project (Chen Bin)

**Comment by langston-barrett** [comment]
@redguardtoo Awesome! Thanks.
