### ISSUE TITLE
Exclude the current line

### ISSUE THREAD

**Issue by Wilfred** [redguardtoo/eacl#2]
`M-x eacl-complete-line` seems to offer the current line too, which isn't very useful :)

**Comment by redguardtoo** [comment]
I think that's fine. That's because the content of current line is saved into file. For performance reason, I don't want to filtering the grepped candidates.

**Comment by Wilfred** [comment]
Would you be open to a PR if it didn't hurt performance?

**Comment by redguardtoo** [comment]
Yes, PR is welcomed.

**Comment by redguardtoo** [comment]
fixed in v1.1.2

**Comment by Wilfred** [comment]
Thank you! :)
